/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokai;

import java.sql.*;
import javax.swing.JTable;
import javax.swing.JOptionPane;
/**
 *
 * @author hinse
 */
public class Consulta_Proveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Proveedor
     */
    public Consulta_Proveedor() {
        initComponents();
        TablaConsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TablaConsulta(){
        // Creamos las variables para cada BD //
        // B1 = SQL //
        Connection B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
        // B2 = MySQL //
        Connection B2 = Conexion.conexion("MySQL", "root", "1310HnBt1809", "TOKAI");
        
        String Titulo[] = new String[2];
        String Datos[][] = new String[2][2];
        
        try{
            if(B1 != null && B2 != null){
                Statement BD1 = B1.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                Statement BD2 = B2.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet RS1 = BD1.executeQuery("select * from Proveedor");
                ResultSet RS2 = BD2.executeQuery("select * from Proveedor");
                if(RS1.next() && RS2.next()){
                    int Columnas1 = RS1.getMetaData().getColumnCount();
                    int Columnas2 = RS2.getMetaData().getColumnCount();
                    int Columnas = (Columnas1 + Columnas2) - 1;
                    Titulo = new String[Columnas];
                    RS1.last();
                    int Filas1 = RS1.getRow();
                    RS2.last();
                    int Filas2 = RS2.getRow();
                    if(Filas1 == Filas2){
                        Datos = new String[Filas2][Columnas];
                        // Llenar titulos //
                        int x = 0;
                        for(int i = 0; i < Columnas1; i++){
                            Titulo[x++] = RS1.getMetaData().getColumnName(i+1);
                        }for(int i = 1; i < Columnas2; i++){
                            Titulo[x++] = RS2.getMetaData().getColumnName(i+1);
                        }
                    RS1.first();
                    RS2.first();
                    int y = Columnas1 - 1;
                    for(int a = 0; a < Filas1; a++){
                        for(int b = 0; b < Columnas1; b++){
                            Datos[a][b] = RS1.getString(b+1);
                        }
                        RS1.next();
                        for(int c = 1; c < Columnas2; c++){
                            Datos[a][y+c] = RS2.getString(c+1);
                        }
                        RS2.next();
                    }
                    jTable1 = new JTable(Datos, Titulo);
                    jScrollPane1.setViewportView(jTable1);
                    }else{
                        System.out.println("Las Tablas Tienen Discrepancia");
                    }
                    // Hasta aqui vamos bien //
                }
            }else{
                JOptionPane.showMessageDialog(null, "No Hay Datos");
            }
        }catch(Exception e){
            System.out.println("Base No Conectada: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
