/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokai;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;

/**
 *
 * @author hinse
 */
public class Consulta_Empleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Empleados
     */
    public Consulta_Empleados() {
        initComponents();
        Buscar();
    }
    
    public void Buscar(){
        // B1 = SQL //
        Connection B1 = null;
        // B2 = MySQL //
        Connection B2 = null;
        
        try{
            B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
            B2 = Conexion.conexion("MySQL", "root", "1310HnBt1809", "TOKAI");
        
            String Titulo[] = new String[2];
            String Datos[][] = new String[2][2];
            
            if(B1 != null && B2 != null){
                Statement BD1 = B1.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                Statement BD2 = B2.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet RS1 = BD1.executeQuery("select * from Empleados");
                ResultSet RS2 = BD2.executeQuery("select * from Empleados");
                if(RS1.next() && RS2.next()){
                    int Columnas1 = RS1.getMetaData().getColumnCount();
                    int Columnas2 = RS2.getMetaData().getColumnCount();
                    int Columnas = (Columnas1 + Columnas2) - 1;
                    Titulo = new String[Columnas];
                    RS1.last();
                    int Filas1 = RS1.getRow();
                    RS2.last();
                    int Filas2 = RS2.getRow();
                    if(Filas1 == Filas2){
                        Datos = new String[Filas2][Columnas];
                        int conC1 = 0;
                        for(int i = 0; i < Columnas1; i++){
                            Titulo[conC1++] = RS1.getMetaData().getColumnName(i+1);
                        }for(int i = 1; i < Columnas2; i++){
                            Titulo[conC1++] = RS2.getMetaData().getColumnName(i+1);
                        }
                    RS1.first();
                    RS2.first();
                    int conC2 = Columnas1 - 1;
                    for(int a = 0; a < Filas1; a++){
                        for(int b = 0; b < Columnas1; b++){
                            Datos[a][b] = RS1.getString(b+1);
                        }
                        RS1.next();
                        for(int c = 1; c < Columnas2; c++){
                            Datos[a][conC2+c] = RS2.getString(c+1);
                        }
                        RS2.next();
                    }
                    jTable1 = new JTable(Datos, Titulo);
                    jScrollPane1.setViewportView(jTable1);
                    }else{
                        System.out.println("No Hay Datos");
                    }
                }
            }else{
                System.out.println("No Existen Datos");
            }
        }catch(Exception e){
            System.out.println("Base No Conectada: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
