/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokai;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author hinse
 */
public class M2_Alta extends javax.swing.JInternalFrame {

    /**
     * Creates new form M2_Alta
     */
    public M2_Alta() {
        initComponents();
    }
    
    public void Buscar(){
        // B1 = SQL //
        Connection B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
        Connection B2 = Conexion.conexion("MySQL", "root", "1310HnBt1809", "TOKAI");
        
        try{
            if(B1 != null && B2 != null){
                PreparedStatement BD1 = B1.prepareStatement("select Correo, Nombre from Empleados where RFC_Empleado = ?");
                PreparedStatement BD2 = B2.prepareStatement("select Nombre_Puesto from Empleados where RFC_Empleado = ?");
                BD1.setString(1, jRFC.getText());
                BD2.setString(1, jRFC.getText());
                // Extrae la información de la BD //
                ResultSet RS1 = BD1.executeQuery();
                ResultSet RS2 = BD2.executeQuery();
                if(RS1.next()){
                    jCorreo.setText(RS1.getString("Correo"));
                    jNombre.setText(RS1.getString("Nombre"));
                }if(RS2.next()){
                    cTipo.setSelectedItem(RS2.getString("Nombre_Puesto"));
                }else{
                    JOptionPane.showMessageDialog(null, "Verificar Numero de Cuenta, No Hay Datos");
                }
            }else{
                System.out.println("Base No Conectada");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRFC = new javax.swing.JTextField();
        jNombre = new javax.swing.JTextField();
        cTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCorreo = new javax.swing.JTextField();
        jAlta = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alta Empleado");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Usuario/RFC");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Tipo");

        jRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFCActionPerformed(evt);
            }
        });

        cTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Cajero", "Almacen" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Correo");

        jAlta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jAlta.setText("Alta");
        jAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAlta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAlta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFCActionPerformed
        Buscar();
    }//GEN-LAST:event_jRFCActionPerformed

    private void jAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaActionPerformed
        Connection B1 = null;
        B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
        
        if(B1 != null){
            try{
                String Pass2 = EncriptarMD5.encripta(jRFC.getText());
               
                CallableStatement BD1 = B1.prepareCall("{Call dbo.AltaAcceso(?,?,?,?,?)}");
                BD1.setString(1, jRFC.getText());                    
                BD1.setString(2, Pass2);
                String Tipo = cTipo.getSelectedItem().toString();
                if(Tipo.equals("Administrador")){
                    BD1.setString(3, "1");
                }if(Tipo.equals("Gerente")){
                    BD1.setString(3, "2");
                }if(Tipo.equals("Cajero")){
                    BD1.setString(3, "3");
                }if(Tipo.equals("Almacen")){
                    BD1.setString(3, "4");
                }
                BD1.setString(4, "A");
                BD1.registerOutParameter(5, Types.VARCHAR);
                BD1.execute();
                String Res1 = BD1.getString(5);
                JOptionPane.showMessageDialog(null, Res1);
                if("Acceso Dado de Alta".equals(Res1)){
                    // Envio de correo //                    
                    String From = "Tu Correo";
                    String Pass = "Tu Contraseña";
                    String To = jCorreo.getText();
                    String Mensaje = "Usuario: " + jRFC.getText() + "\nContraseña: " + Pass2;
                
                    SSLEmail.enviar(From, Pass, To, Mensaje);
                    // Envio de correo //
                }
            }catch(Exception e){
                System.out.println("Error: " + e);
                System.out.println("Registro no Realizado");
            }
        }else{
            System.out.println("Base No Conectada");
        } 
    }//GEN-LAST:event_jAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cTipo;
    private javax.swing.JButton jAlta;
    private javax.swing.JTextField jCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNombre;
    private javax.swing.JTextField jRFC;
    // End of variables declaration//GEN-END:variables
}
