/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokai;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author hinse
 */
public class Salidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Salidas
     */
    public Salidas() {
        initComponents();
        cEmpleados = Conexion.LlenarCB("select Nombre from Empleados", cEmpleados, "TOKAI", "sa", "180926", "SQL");
        cCantidad.removeAllItems();
        for(int i = 1; i <= 30; i++){
            cCantidad.addItem("" + i);
        }
    }
    
    public void BuscarS(){
        // B1 = SQL //
        Connection B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
        
        if(B1 != null){
            try{
                Statement st = B1.createStatement();
                //Este código es el que extrae la informacion de SQL
                ResultSet rs = st.executeQuery("select RFC_Proveedor, Producto from Almacen_Producto where "
                        + "SKU = '" + jSKU.getText() + "'");
                if(rs.next()){
                    jProveedor.setText(rs.getString("RFC_Proveedor"));
                    jProducto.setText(rs.getString("Producto"));
                }else{
                    System.out.println("No hay datos");
                }
            }catch(Exception e){
                System.out.println("Error: " + e);
            }
        }else{
            System.out.println("Base No Conectada");
        }
    }
    
    public void BuscarP(){
        // B1 = SQL //
        Connection B2 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");
        
        if(B2 != null){
            try{
                Statement st2 = B2.createStatement();
                //Este código es el que extrae la informacion de SQL
                ResultSet rs2 = st2.executeQuery("select Nombre from Proveedor where "
                        + "RFC_Proveedor = '" + jProveedor.getText() + "'");
                if(rs2.next()){
                    jNProveedor.setText(rs2.getString("Nombre"));
                }else{
                    System.out.println("No hay datos");
                }
            }catch(Exception e){
                System.out.println("Error: " + e);
            }
        }else{
            System.out.println("Base No Conectada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSKU = new javax.swing.JTextField();
        jNProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jProducto = new javax.swing.JTextField();
        cEmpleados = new javax.swing.JComboBox<>();
        jEntradas = new javax.swing.JButton();
        cCantidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFechaS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Producto");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Cantidad");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AAAA/MM/DD");

        jSKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSKUActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Empleado Solicitante");

        jEntradas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jEntradas.setText("Salida");
        jEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntradasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salida de Producto");

        jProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProveedorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("SKU");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Proveedor");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Fecha Salida");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Nombre Proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEntradas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEntradas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSKUActionPerformed
        BuscarS();
    }//GEN-LAST:event_jSKUActionPerformed

    private void jEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntradasActionPerformed
        // B1 = SQL //
        Connection B1 = null;
        Connection B2 = null;

        try{
            B1 = Conexion.conexion("SQL", "sa", "180926", "TOKAI");

            if(B1 != null){
                CallableStatement BD1 = B1.prepareCall("{Call dbo.Salida(?,?,?,?,?,?,?)}");
                BD1.setString(1, jSKU.getText());
                BD1.setString(2, jProveedor.getText());
                BD1.setString(3, jProducto.getText());
                BD1.setString(4, cCantidad.getSelectedItem().toString());
                BD1.setString(5, jFechaS.getText());
                BD1.setString(6, cEmpleados.getSelectedItem().toString());
                BD1.registerOutParameter(7, Types.VARCHAR);
                BD1.execute();
                String Res1 = BD1.getString(7);
                JOptionPane.showMessageDialog(null, Res1);
            }else{
                JOptionPane.showMessageDialog(null, "Verificar Datos, Alta No Realizada");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_jEntradasActionPerformed

    private void jProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProveedorActionPerformed
        BuscarP();
    }//GEN-LAST:event_jProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cCantidad;
    private javax.swing.JComboBox<String> cEmpleados;
    private javax.swing.JButton jEntradas;
    private javax.swing.JTextField jFechaS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNProveedor;
    private javax.swing.JTextField jProducto;
    private javax.swing.JTextField jProveedor;
    private javax.swing.JTextField jSKU;
    // End of variables declaration//GEN-END:variables
}
